pipeline {
    agent none

    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                sh 'mvn --version'

                script {
                    // Java Hello, World!
                    writeFile file: 'pom.xml', text: '''
                    <project xmlns="http://maven.apache.org/POM/4.0.0"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                        <modelVersion>4.0.0</modelVersion>
                        <groupId>com.example</groupId>
                        <artifactId>hello-world-java</artifactId>
                        <version>1.0-SNAPSHOT</version>
                        <properties>
                            <maven.compiler.source>1.8</maven.compiler.source>
                            <maven.compiler.target>1.8</maven.compiler.target>
                        </properties>
                    </project>
                    '''
                    
                    writeFile file: 'src/main/java/HelloWorld.java', text: '''
                    public class HelloWorld {
                        public static void main(String[] args) {
                            System.out.println("Hello, World from Java!");
                        }
                    }
                    '''
                    
                    sh 'mvn clean install'
               
                }
            }
        }
    }
}
